version: '3'
services:
  talana-kombat:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "talana-kombat"
    entrypoint: ../entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/www